# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 
author: Nathan Branco Caracho
logo: assets/logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'auto'

# Information about where the book exists on the web
repository:
  url: https://github.com/nathancaracho/devman # Online location of your book
  path_to_book: docs  
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

